version: '3.3'
services:
  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postpass
      POSTGRES_DB: websystem
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  back:
    container_name: back
    build: backend/.
    restart: always
    ports:
      - "8080:3000"
    depends_on:
      - database
  front:
    build: frontend/.
    ports:
      - "80:80"
    depends_on:
      - back
