service: nestjs-graphql-serverless-postgresql
app: angular-nest-js-prisma-dev
org: niknicius

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  vpc:
    securityGroupIds:
      - sg-3699951e
    subnetIds:
      - subnet-12d6051c
      - subnet-18c7ea26
      - subnet-1b59407c
  profile: default # Config your AWS Profile
  environment: # Service wide environment variables
    NODE_ENV: production

plugins:
  - serverless-offline

package:
  exclude:
    - .git/**
    - src/**
    - test/**
    - nodemon.json
    - README.md
  excludeDevDependencies: true

functions:
  index:
    handler: dist/serverless.handler
    events:
      - http:
          cors: true
          path: '/{proxy+}'
          method: any

resources:
  Resources:
    AWSLambdaVPCAccessExecutionRole:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        Description: Creating policy for vpc connetion.
        Roles:
          - {"Ref" : "IamRoleLambdaExecution"}
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ec2:CreateNetworkInterface
                - ec2:DescribeNetworkInterfaces
                - ec2:DeleteNetworkInterface
              Resource: "*"
